// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ValidLoginTestcaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void validLoginTestcase() {
    // Test name: Valid Login Testcase
    // Step # | name | target | value
    // 1 | open | http://automationpractice.com/index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 974x1040 | 
    driver.manage().window().setSize(new Dimension(974, 1040));
    // 3 | click | linkText=Sign in | 
    driver.findElement(By.linkText("Sign in")).click();
    // 4 | click | css=.form_content > .form-group:nth-child(1) | 
    driver.findElement(By.cssSelector(".form_content > .form-group:nth-child(1)")).click();
    // 5 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 6 | type | id=email | abc44444@gmail.com
    driver.findElement(By.id("email")).sendKeys("abc44444@gmail.com");
    // 7 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 8 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 9 | type | id=passwd | xyzaas
    driver.findElement(By.id("passwd")).sendKeys("xyzaas");
    // 10 | click | css=#SubmitLogin > span | 
    driver.findElement(By.cssSelector("#SubmitLogin > span")).click();
    // 11 | click | css=.footer_links | 
    driver.findElement(By.cssSelector(".footer_links")).click();
    // 12 | click | linkText=Sign out | 
    driver.findElement(By.linkText("Sign out")).click();
  }
}
