// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ValidTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void valid() {
    driver.get("https://phptravels.org/register.php");
    driver.manage().window().setSize(new Dimension(974, 1040));
    driver.findElement(By.id("inputFirstName")).sendKeys("Ninad");
    driver.findElement(By.id("inputLastName")).click();
    driver.findElement(By.id("inputLastName")).sendKeys("Patil");
    driver.findElement(By.id("inputEmail")).click();
    driver.findElement(By.id("inputEmail")).sendKeys("abc98@gmail.com");
    driver.findElement(By.cssSelector(".selected-flag > .iti-flag")).click();
    driver.findElement(By.cssSelector(".highlight > .country-name")).click();
    driver.findElement(By.id("inputPhone")).click();
    driver.findElement(By.id("inputPhone")).sendKeys("8097502143");
    driver.findElement(By.id("inputAddress1")).click();
    driver.findElement(By.id("inputAddress1")).sendKeys("Chembur. Gaothan");
    driver.findElement(By.id("inputCity")).click();
    driver.findElement(By.id("inputCity")).sendKeys("Mumbai");
    driver.findElement(By.id("stateinput")).click();
    driver.findElement(By.id("stateinput")).sendKeys("Maharashtra");
    driver.findElement(By.id("inputPostcode")).click();
    driver.findElement(By.id("inputPostcode")).sendKeys("400071");
    driver.findElement(By.id("inputCountry")).click();
    {
      WebElement dropdown = driver.findElement(By.id("inputCountry"));
      dropdown.findElement(By.xpath("//option[. = 'India']")).click();
    }
    driver.findElement(By.id("inputCountry")).click();
    driver.findElement(By.cssSelector(".row:nth-child(6) > .col-sm-6:nth-child(1) > .form-group")).click();
    driver.findElement(By.id("customfield1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("customfield1"));
      dropdown.findElement(By.xpath("//option[. = 'Google']")).click();
    }
    driver.findElement(By.id("customfield2")).click();
    driver.findElement(By.id("customfield2")).sendKeys("8097502143");
    driver.findElement(By.id("inputNewPassword1")).click();
    driver.findElement(By.id("inputNewPassword1")).sendKeys("abc1998");
    driver.findElement(By.id("inputNewPassword2")).click();
    js.executeScript("window.scrollTo(0,623)");
    driver.findElement(By.id("inputNewPassword2")).sendKeys("abc1998");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".recaptcha-checkbox-checkmark")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector(".btn-large")).click();
    driver.close();
  }
}
